### Testes do FluxoEngine - Infinity Dialog
### Baseado nos dados criados pelo seed
@microservice-token=dad38516a8c9a39564f4dbfa52b568e5748500d73e32be3096a36a4cb7d4d1fd2f04740614172e15be5a8e589cbd600c314aedcd942c2c90eb596b850f17063b

@tenant_id=123e4567-e89b-12d3-a456-426614174000

### FLUXOS
### LISTAR TODOS OS FLUXOS DISPONÍVEIS
POST http://localhost:3000/fluxo/find
Content-Type: application/json
x-microservice-token: {{microservice-token}}

{
  "page": 1,
  "limit": 10,
  "search": "",
  "tenant_id": "{{tenant_id}}"
}

### LISTAR POR FLUXO ID
GET http://localhost:3000/fluxo/06d4771b-a27d-4eea-998d-a832613642b3
Content-Type: application/json
x-microservice-token: {{microservice-token}}

### CRIA FLUXO
POST http://localhost:3000/fluxo/create
Content-Type: application/json
x-microservice-token: {{microservice-token}}

{
  "tenant_id": "{{tenant_id}}",
  "nome": "Fluxo de Teste"
}

### ATUALIZAR CONFIGURAÇÃO DO FLUXO
PUT http://localhost:3000/fluxo/configuracao
Content-Type: application/json
x-microservice-token: {{microservice-token}}

{
  "configuracoes": [
    {
      "id": "21e235b2-50bd-49b1-98cf-5cee5fc80219",
      "valor": "Seu atendimento foi encaminhado para um dos nossos atendentes. Aguarde a resposta do atendente."
    },
    {
      "id": "dc037e3e-a96d-49a7-a7e2-523393497877",
      "valor": "Resposta inválida, escolha uma das opções disponíveis."
    }
  ]
}